{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "request_id",
    "label": "RequestId",
    "query": "069d830d-6e3f-7831-8000-d67c31819ef1"
   }
  ]
 },
 "panels": [
  {
   "title": "Journey of a request by request_id (Add RequestId at the bottom of this dashboard)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{compose_project=\"gentleman-stack\"}\r\n| json\r\n| request_id = \"${request_id}\""
    }
   ]
  },
  {
   "title": "#Q of Received events over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n    {service_name=\"app\"} \r\n    | json\r\n    | event = \"ingest_started\"\r\n\r\n    [$__auto])\r\n# {\"text_desc_length\": 13, \"num_attachments\": 0, \"event\": \"ingest_started\", \"phase\": \"ingest\", \"component\": \"api\", \"request_id\": \"069d82a7-e745-725a-8000-ad4cc130df8d\", \"service\": \"backend\", \"level\": \"info\", \"timestamp\": \"2026-04-09T22:38:54.455952Z\"}\r\n"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n    {service_name=\"app\"} \r\n    | json\r\n    | event = \"relevance_check_rejected\"\r\n\r\n    [$__auto])\r\n# {\"text_desc_length\": 13, \"num_attachments\": 0, \"event\": \"ingest_started\", \"phase\": \"ingest\", \"component\": \"api\", \"request_id\": \"069d82a7-e745-725a-8000-ad4cc130df8d\", \"service\": \"backend\", \"level\": \"info\", \"timestamp\": \"2026-04-09T22:38:54.455952Z\"}\r\n\r\n\r\n# {\"reason\": \"not_sre_incident\", \"event\": \"relevance_check_rejected\", \"phase\": \"ingest\", \"component\": \"api\", \"request_id\": \"069d8301-9b69-7880-8000-3b597e7109f0\", \"service\": \"backend\", \"level\": \"warning\", \"timestamp\": \"2026-04-09T23:02:53.669062Z\"} \r\n"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n    {service_name=\"app\"} \r\n    | json\r\n    | event = \"relevance_check_passed\"\r\n    [$__auto])\r\n# {\"event\": \"relevance_check_passed\", \"phase\": \"ingest\", \"component\": \"api\", \"request_id\": \"069d830d-6e3f-7831-8000-d67c31819ef1\", \"service\": \"backend\", \"level\": \"info\", \"timestamp\": \"2026-04-09T23:06:01.975852Z\"}"
    }
   ]
  },
  {
   "title": "#Q of tools called over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (tool) (\r\n  count_over_time(\r\n    {service_name=\"app\"} \r\n    | json\r\n    | event = \"tool_execution\"\r\n    | status = \"started\"\r\n    [$__auto]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "These are the logs from the Agentic stack",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{compose_project=\"gentleman-stack\"} |= ``"
    }
   ]
  }
 ]
}