server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_pass http://sre-api:8000/auth/;
    }

    location /reports/ {
        proxy_pass http://sre-api:8000/reports/;
    }
}
